remote_theme: pages-themes/cayman@v0.3.0
plugins:
  - jekyll-remote-theme
title: The Ethics of Exploit
author: Emma Trowbridge

markdown: kramdown
kramdown:
  input: GFM
  footnote_backlink: "↩"
  footnote_nr: 1
